default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anchietajunior_development
  host: localhost
  username: postgres
  password: postgres
  port: 5432

test:
  <<: *default
  database: anchietajunior_test
  host: localhost
  username: postgres
  password: postgres
  port: 5432

production:
  <<: *default
  database: anchietajunior
  username: deploy
  password: <%= ENV['ANCHIETAJUNIOR_DATABASE_PASSWORD'] %>
